"""
migrate_xlsx_to_sqlite.py — One-time migration from .xlsx files to data/finance.db

Run once after all xlsx files have been generated by the pipeline:
    python migrate_xlsx_to_sqlite.py

The script is idempotent: running it again will replace existing tables
(IF_EXISTS='replace'), so it is safe to re-run after a fresh pipeline run.

Table naming convention:
  transactions          ← transactions.xlsx (Sheet: Transactions)
  livret_a              ← livret_a_transactions.xlsx
  features_full         ← features.xlsx / Full Data
  feature_matrix        ← features.xlsx / Feature Matrix
  monthly_aggregates    ← features.xlsx / Monthly Aggregates
  category_summary      ← features.xlsx / Category Summary
  model_comparison      ← model_results.xlsx / Model Comparison
  lr_report             ← model_results.xlsx / Logistic Regression Report
  rf_report             ← model_results.xlsx / Random Forest Report
  xgb_report            ← model_results.xlsx / XGBoost Report
  confusion_matrix      ← model_results.xlsx / Confusion Matrix
  rf_feature_importance ← model_results.xlsx / RF Feature Importance
  xgb_feature_importance← model_results.xlsx / XGB Feature Importance
  cross_validation      ← model_results.xlsx / Cross Validation
  nlp_results           ← nlp_results.xlsx / NLP Comparison
  monthly_credit        ← creditworthiness_results.xlsx / Monthly Credit Profile
  credit_scores         ← creditworthiness_results.xlsx / Credit Scores
  credit_features       ← creditworthiness_results.xlsx / Credit Features
  credit_summary        ← creditworthiness_results.xlsx / Credit Summary
  cashflow_metrics      ← cashflow_results.xlsx / Regression Metrics
  cashflow_predictions  ← cashflow_results.xlsx / Actual vs Predicted
  cashflow_forecast     ← cashflow_results.xlsx / Next Month Forecast
  cashflow_features_imp ← cashflow_results.xlsx / Feature Importance
  anomaly_results       ← anomaly_results.xlsx / Anomaly Results
  anomaly_summary       ← anomaly_results.xlsx / Summary
"""

import sqlite3
import pandas as pd
from pathlib import Path

from src.config import (
    DATA_DIR, FINANCE_DB,
    TRANSACTIONS_XLSX, FEATURES_XLSX, LIVRET_A_XLSX,
    MODEL_RESULTS_XLSX, NLP_RESULTS_XLSX,
    CREDITWORTHINESS_XLSX, CASHFLOW_RESULTS_XLSX, ANOMALY_RESULTS_XLSX,
)


def load_sheet(xlsx_path: Path, sheet_name: str, **kwargs) -> pd.DataFrame | None:
    """Load an Excel sheet; return None if file or sheet doesn't exist."""
    if not xlsx_path.exists():
        return None
    try:
        return pd.read_excel(xlsx_path, sheet_name=sheet_name, **kwargs)
    except Exception as e:
        print(f"  [skip] {xlsx_path.name} / {sheet_name!r}: {e}")
        return None


def write(con: sqlite3.Connection, table: str, df: pd.DataFrame | None):
    if df is None or df.empty:
        print(f"  [skip] {table} — no data")
        return
    df.to_sql(table, con, if_exists='replace', index=False)
    print(f"  [ok]   {table:<30} {len(df):>6} rows")


def migrate():
    DATA_DIR.mkdir(exist_ok=True)
    print("=" * 60)
    print("MIGRATING .xlsx → data/finance.db")
    print("=" * 60)

    con = sqlite3.connect(FINANCE_DB)

    # ── transactions.xlsx ────────────────────────────────────────────────────
    print("\n[transactions.xlsx]")
    write(con, "transactions",    load_sheet(TRANSACTIONS_XLSX, "Transactions"))

    # ── livret_a_transactions.xlsx ───────────────────────────────────────────
    print("\n[livret_a_transactions.xlsx]")
    write(con, "livret_a",        load_sheet(LIVRET_A_XLSX, 0))

    # ── features.xlsx ────────────────────────────────────────────────────────
    print("\n[features.xlsx]")
    write(con, "features_full",       load_sheet(FEATURES_XLSX, "Full Data"))
    write(con, "feature_matrix",      load_sheet(FEATURES_XLSX, "Feature Matrix"))
    write(con, "monthly_aggregates",  load_sheet(FEATURES_XLSX, "Monthly Aggregates"))
    write(con, "category_summary",    load_sheet(FEATURES_XLSX, "Category Summary"))

    # ── model_results.xlsx ───────────────────────────────────────────────────
    print("\n[model_results.xlsx]")
    write(con, "model_comparison",      load_sheet(MODEL_RESULTS_XLSX, "Model Comparison"))
    write(con, "lr_report",             load_sheet(MODEL_RESULTS_XLSX, "Logistic Regression Report"))
    write(con, "rf_report",             load_sheet(MODEL_RESULTS_XLSX, "Random Forest Report"))
    write(con, "xgb_report",            load_sheet(MODEL_RESULTS_XLSX, "XGBoost Report"))
    write(con, "confusion_matrix",      load_sheet(MODEL_RESULTS_XLSX, "Confusion Matrix"))
    write(con, "rf_feature_importance", load_sheet(MODEL_RESULTS_XLSX, "RF Feature Importance"))
    write(con, "xgb_feature_importance",load_sheet(MODEL_RESULTS_XLSX, "XGB Feature Importance"))
    write(con, "cross_validation",      load_sheet(MODEL_RESULTS_XLSX, "Cross Validation"))

    # ── nlp_results.xlsx ─────────────────────────────────────────────────────
    print("\n[nlp_results.xlsx]")
    write(con, "nlp_results",     load_sheet(NLP_RESULTS_XLSX, 0))

    # ── creditworthiness_results.xlsx ────────────────────────────────────────
    print("\n[creditworthiness_results.xlsx]")
    write(con, "monthly_credit",  load_sheet(CREDITWORTHINESS_XLSX, "Monthly Credit Profile"))
    write(con, "credit_scores",   load_sheet(CREDITWORTHINESS_XLSX, "Credit Scores"))
    write(con, "credit_features", load_sheet(CREDITWORTHINESS_XLSX, "Credit Features"))
    write(con, "credit_summary",  load_sheet(CREDITWORTHINESS_XLSX, "Credit Summary"))

    # ── cashflow_results.xlsx ────────────────────────────────────────────────
    print("\n[cashflow_results.xlsx]")
    write(con, "cashflow_metrics",     load_sheet(CASHFLOW_RESULTS_XLSX, "Regression Metrics"))
    write(con, "cashflow_predictions", load_sheet(CASHFLOW_RESULTS_XLSX, "Actual vs Predicted"))
    write(con, "cashflow_forecast",    load_sheet(CASHFLOW_RESULTS_XLSX, "Next Month Forecast"))
    write(con, "cashflow_feature_imp", load_sheet(CASHFLOW_RESULTS_XLSX, "Feature Importance"))

    # ── anomaly_results.xlsx ─────────────────────────────────────────────────
    print("\n[anomaly_results.xlsx]")
    write(con, "anomaly_results",  load_sheet(ANOMALY_RESULTS_XLSX, "Anomaly Results"))
    write(con, "anomaly_summary",  load_sheet(ANOMALY_RESULTS_XLSX, "Summary"))

    con.close()

    size_kb = FINANCE_DB.stat().st_size / 1024
    print(f"\n{'='*60}")
    print(f"Migration complete → {FINANCE_DB}")
    print(f"Database size: {size_kb:.1f} KB")
    print(f"{'='*60}")


if __name__ == "__main__":
    migrate()
